// AUTO-GENERATED by scripts/convert-zones-to-ts.py
// Source: factory_ai/output/zones/*.json + tile_mappings.json
// DO NOT EDIT by hand — re-run the converter to regenerate.

export interface PropPlacement {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  layer: 'below' | 'above';
  anchors: { name: string; ox: number; oy: number; type: 'work' | 'rest' | 'social' | 'utility' | 'wander' }[];
}

// ─── Data Center (rows 1-8, cols 1-9) ───
export const dataCenterProps: PropPlacement[] = [
  { id: "server_rack", x: 2, y: 2, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_0", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 4, y: 2, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_1", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 6, y: 2, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_2", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 8, y: 2, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_3", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 2, y: 5, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_4", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 4, y: 5, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_5", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 6, y: 5, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_6", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "server_rack", x: 8, y: 5, w: 1, h: 2, layer: 'below', anchors: [{ name: "dc_rack_7", ox: 0.5, oy: 2.5, type: 'utility' }] },
  { id: "cooling_unit", x: 1, y: 3, w: 1, h: 2, layer: 'below', anchors: [] },
  { id: "cooling_unit", x: 1, y: 6, w: 1, h: 2, layer: 'below', anchors: [] },
  { id: "monitoring_desk", x: 7, y: 7.5, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "dc_monitor", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 8, y: 8.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "biometric_panel", x: 1, y: 1, w: 0.5, h: 1, layer: 'below', anchors: [] },
];

// ─── Auditorium (rows 1-8, cols 11-19) ───
export const auditoriumProps: PropPlacement[] = [
  { id: "projection_screen", x: 12, y: 1, w: 6, h: 1, layer: 'below', anchors: [] },
  { id: "podium", x: 14.5, y: 3, w: 2, h: 1, layer: 'below', anchors: [{ name: "podium_speaker", ox: 1, oy: 1.5, type: 'work' }] },
  { id: "auditorium_seats", x: 12, y: 4, w: 6, h: 1, layer: 'below', anchors: [
    { name: "aud_seat_0", ox: 1, oy: 0, type: 'social' },
    { name: "aud_seat_1", ox: 3, oy: 0, type: 'social' },
    { name: "aud_seat_2", ox: 5, oy: 0, type: 'social' },
    ] },
  { id: "auditorium_seats", x: 12, y: 5.5, w: 6, h: 1, layer: 'below', anchors: [
    { name: "aud_seat_3", ox: 1, oy: 0, type: 'social' },
    { name: "aud_seat_4", ox: 3, oy: 0, type: 'social' },
    { name: "aud_seat_5", ox: 5, oy: 0, type: 'social' },
    ] },
  { id: "auditorium_seats", x: 12, y: 7, w: 6, h: 1, layer: 'below', anchors: [
    { name: "aud_seat_6", ox: 1, oy: 0, type: 'social' },
    { name: "aud_seat_7", ox: 3, oy: 0, type: 'social' },
    { name: "aud_seat_8", ox: 5, oy: 0, type: 'social' },
    ] },
  { id: "av_control_booth", x: 17, y: 8, w: 2, h: 2, layer: 'below', anchors: [{ name: "av_operator", ox: 1, oy: 1, type: 'work' }] },
  { id: "ceiling_speaker", x: 11, y: 2, w: 1, h: 0.5, layer: 'above', anchors: [] },
  { id: "ceiling_speaker", x: 18, y: 2, w: 1, h: 0.5, layer: 'above', anchors: [] },
  { id: "lighting_control", x: 11, y: 7, w: 1, h: 1, layer: 'below', anchors: [] },
];

// ─── Noc War Room (rows 1-8, cols 21-29) ───
export const nocProps: PropPlacement[] = [
  { id: "noc_screen_wall", x: 22, y: 1, w: 6, h: 2, layer: 'below', anchors: [] },
  { id: "war_table", x: 24, y: 4, w: 3, h: 2, layer: 'below', anchors: [
    { name: "war_seat_0", ox: 0, oy: 2.5, type: 'work' },
    { name: "war_seat_1", ox: 1.5, oy: 2.5, type: 'work' },
    { name: "war_seat_2", ox: 3, oy: 2.5, type: 'work' },
    { name: "war_seat_3", ox: 0, oy: -0.5, type: 'work' },
    { name: "war_seat_4", ox: 1.5, oy: -0.5, type: 'work' },
    { name: "war_seat_5", ox: 3, oy: -0.5, type: 'work' },
    ] },
  { id: "monitor_workstation", x: 21, y: 6, w: 3, h: 1.5, layer: 'below', anchors: [{ name: "noc_work_0", ox: 1.5, oy: 2, type: 'work' }] },
  { id: "monitor_workstation", x: 25, y: 6, w: 3, h: 1.5, layer: 'below', anchors: [{ name: "noc_work_1", ox: 1.5, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 22.5, y: 8, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "ergonomic_chair", x: 26.5, y: 8, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "alert_dashboard", x: 28, y: 1, w: 1, h: 3, layer: 'below', anchors: [] },
  { id: "communication_panel", x: 21, y: 1, w: 1, h: 2, layer: 'below', anchors: [] },
];

// ─── Scrum Room (rows 1-8, cols 31-38) ───
export const scrumProps: PropPlacement[] = [
  { id: "standing_desk", x: 32, y: 2, w: 2, h: 1, layer: 'below', anchors: [{ name: "scrum_stand_0", ox: 1, oy: 1.5, type: 'work' }] },
  { id: "standing_desk", x: 35, y: 2, w: 2, h: 1, layer: 'below', anchors: [{ name: "scrum_stand_1", ox: 1, oy: 1.5, type: 'work' }] },
  { id: "standing_desk", x: 32, y: 4, w: 2, h: 1, layer: 'below', anchors: [{ name: "scrum_stand_2", ox: 1, oy: 1.5, type: 'work' }] },
  { id: "standing_desk", x: 35, y: 4, w: 2, h: 1, layer: 'below', anchors: [{ name: "scrum_stand_3", ox: 1, oy: 1.5, type: 'work' }] },
  { id: "whiteboard_wall", x: 31, y: 1, w: 7, h: 1, layer: 'below', anchors: [] },
  { id: "whiteboard_wall", x: 31, y: 6, w: 7, h: 1, layer: 'below', anchors: [] },
  { id: "sprint_board", x: 31, y: 3, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "sprint_board", x: 37, y: 3, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "mobile_stool", x: 33, y: 6, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "mobile_stool", x: 34, y: 6, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "mobile_stool", x: 35, y: 6, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "mobile_stool", x: 36, y: 6, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "digital_display", x: 34, y: 7, w: 1.5, h: 0.5, layer: 'below', anchors: [] },
  { id: "sticky_note_dispenser", x: 31, y: 2, w: 0.5, h: 0.5, layer: 'below', anchors: [] },
  { id: "sticky_note_dispenser", x: 37.5, y: 2, w: 0.5, h: 0.5, layer: 'below', anchors: [] },
];

// ─── Open Cowork (rows 11-18, cols 1-14) ───
export const coworkProps: PropPlacement[] = [
  { id: "desk_monitor", x: 2, y: 12, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "cowork_desk_0", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 3, y: 14, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "desk_monitor", x: 6, y: 12, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "cowork_desk_1", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 7, y: 14, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "desk_monitor", x: 10, y: 12, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "cowork_desk_2", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 11, y: 14, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "desk_monitor", x: 2, y: 16, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "cowork_desk_3", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 3, y: 18, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "desk_monitor", x: 6, y: 16, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "cowork_desk_4", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 7, y: 18, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "desk_monitor", x: 10, y: 16, w: 2.5, h: 1.5, layer: 'below', anchors: [{ name: "cowork_desk_5", ox: 1.25, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 11, y: 18, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "phone_booth", x: 1, y: 14, w: 2, h: 2, layer: 'below', anchors: [{ name: "phone_0", ox: 1, oy: 1, type: 'work' }] },
  { id: "phone_booth", x: 13, y: 14, w: 2, h: 2, layer: 'below', anchors: [{ name: "phone_1", ox: 1, oy: 1, type: 'work' }] },
  { id: "collaboration_table", x: 5, y: 14.5, w: 3, h: 1.5, layer: 'below', anchors: [
    { name: "collab_0", ox: 0, oy: 2, type: 'social' },
    { name: "collab_1", ox: 3, oy: 2, type: 'social' },
    ] },
  { id: "tall_plant", x: 1, y: 11, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "tall_plant", x: 13, y: 11, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "storage_locker", x: 1, y: 17, w: 3, h: 0.5, layer: 'below', anchors: [] },
  { id: "storage_locker", x: 11, y: 17, w: 3, h: 0.5, layer: 'below', anchors: [] },
];

// ─── Ceo Office (rows 11-18, cols 16-22) ───
export const ceoProps: PropPlacement[] = [
  { id: "executive_desk", x: 17, y: 12, w: 3.5, h: 2, layer: 'below', anchors: [{ name: "ceo_desk", ox: 1.75, oy: 2.5, type: 'work' }] },
  { id: "executive_chair", x: 18.25, y: 14.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "l_shaped_sofa", x: 19, y: 16, w: 4, h: 3, layer: 'below', anchors: [
    { name: "ceo_sofa_0", ox: 1, oy: 0, type: 'rest' },
    { name: "ceo_sofa_1", ox: 3, oy: 0, type: 'rest' },
    ] },
  { id: "coffee_table", x: 20, y: 14.5, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "bookshelf", x: 16, y: 11, w: 6, h: 0.5, layer: 'below', anchors: [] },
  { id: "meeting_table", x: 16.5, y: 16, w: 2, h: 2, layer: 'below', anchors: [
    { name: "ceo_meet_0", ox: 0, oy: 2.5, type: 'social' },
    { name: "ceo_meet_1", ox: 2, oy: 2.5, type: 'social' },
    ] },
  { id: "meeting_chair", x: 16.5, y: 18.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "meeting_chair", x: 18.5, y: 18.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "art_display", x: 21, y: 11, w: 3, h: 2, layer: 'below', anchors: [] },
  { id: "mini_fridge", x: 22, y: 17, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "tall_plant", x: 16, y: 18, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "tall_plant", x: 22, y: 12, w: 1, h: 1, layer: 'below', anchors: [] },
];

// ─── Huddle Pods (rows 11-18, cols 24-38) ───
export const huddleProps: PropPlacement[] = [
  { id: "huddle_glass_wall", x: 24, y: 11, w: 0.5, h: 4, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 29, y: 11, w: 0.5, h: 4, layer: 'below', anchors: [] },
  { id: "round_table", x: 25.5, y: 12, w: 2, h: 2, layer: 'below', anchors: [
    { name: "huddle_0_a", ox: 0, oy: 2.5, type: 'social' },
    { name: "huddle_0_b", ox: 2, oy: 2.5, type: 'social' },
    { name: "huddle_0_c", ox: -0.5, oy: 1, type: 'social' },
    { name: "huddle_0_d", ox: 2.5, oy: 1, type: 'social' },
    ] },
  { id: "pod_chair", x: 25.5, y: 14.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 27.5, y: 14.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 25, y: 13, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 28, y: 13, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "wall_screen", x: 26.5, y: 11, w: 1, h: 0.5, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 31, y: 11, w: 0.5, h: 4, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 36, y: 11, w: 0.5, h: 4, layer: 'below', anchors: [] },
  { id: "round_table", x: 32.5, y: 12, w: 2, h: 2, layer: 'below', anchors: [
    { name: "huddle_1_a", ox: 0, oy: 2.5, type: 'social' },
    { name: "huddle_1_b", ox: 2, oy: 2.5, type: 'social' },
    { name: "huddle_1_c", ox: -0.5, oy: 1, type: 'social' },
    { name: "huddle_1_d", ox: 2.5, oy: 1, type: 'social' },
    ] },
  { id: "pod_chair", x: 32.5, y: 14.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 34.5, y: 14.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 32, y: 13, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 35, y: 13, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "wall_screen", x: 33.5, y: 11, w: 1, h: 0.5, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 24, y: 16, w: 0.5, h: 3, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 29, y: 16, w: 0.5, h: 3, layer: 'below', anchors: [] },
  { id: "round_table", x: 25.5, y: 16.5, w: 2, h: 2, layer: 'below', anchors: [
    { name: "huddle_2_a", ox: 0, oy: 2.5, type: 'social' },
    { name: "huddle_2_b", ox: 2, oy: 2.5, type: 'social' },
    { name: "huddle_2_c", ox: -0.5, oy: 1, type: 'social' },
    { name: "huddle_2_d", ox: 2.5, oy: 1, type: 'social' },
    ] },
  { id: "pod_chair", x: 25.5, y: 19, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 27.5, y: 19, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 25, y: 17.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 28, y: 17.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "whiteboard", x: 26.5, y: 16, w: 1, h: 0.5, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 31, y: 16, w: 0.5, h: 3, layer: 'below', anchors: [] },
  { id: "huddle_glass_wall", x: 36, y: 16, w: 0.5, h: 3, layer: 'below', anchors: [] },
  { id: "round_table", x: 32.5, y: 16.5, w: 2, h: 2, layer: 'below', anchors: [
    { name: "huddle_3_a", ox: 0, oy: 2.5, type: 'social' },
    { name: "huddle_3_b", ox: 2, oy: 2.5, type: 'social' },
    { name: "huddle_3_c", ox: -0.5, oy: 1, type: 'social' },
    { name: "huddle_3_d", ox: 2.5, oy: 1, type: 'social' },
    ] },
  { id: "pod_chair", x: 32.5, y: 19, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 34.5, y: 19, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 32, y: 17.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "pod_chair", x: 35, y: 17.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "whiteboard", x: 33.5, y: 16, w: 1, h: 0.5, layer: 'below', anchors: [] },
];

// ─── Snack Bar (rows 20-24, cols 1-5) ───
export const snackProps: PropPlacement[] = [
  { id: "l_counter", x: 1.5, y: 21, w: 3.5, h: 1, layer: 'below', anchors: [
    { name: "snack_seat_0", ox: 1, oy: 1.5, type: 'utility' },
    { name: "snack_seat_1", ox: 2.5, oy: 1.5, type: 'utility' },
    ] },
  { id: "bar_stool", x: 2.5, y: 22.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "bar_stool", x: 4, y: 22.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "commercial_fridge", x: 1, y: 20, w: 1, h: 1.5, layer: 'below', anchors: [] },
  { id: "microwave", x: 2, y: 20, w: 0.5, h: 0.5, layer: 'below', anchors: [] },
  { id: "coffee_machine", x: 3, y: 20, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "prep_sink", x: 4.5, y: 20, w: 0.5, h: 0.5, layer: 'below', anchors: [] },
  { id: "storage_cabinet", x: 1, y: 23, w: 4, h: 0.5, layer: 'below', anchors: [] },
  { id: "storage_cabinet", x: 1, y: 19.5, w: 4, h: 0.5, layer: 'below', anchors: [] },
];

// ─── Cafe (rows 20-24, cols 7-13) ───
export const cafeProps: PropPlacement[] = [
  { id: "cafe_table", x: 8, y: 21, w: 1.5, h: 1.5, layer: 'below', anchors: [
    { name: "cafe_seat_0", ox: -0.5, oy: 0.75, type: 'social' },
    { name: "cafe_seat_1", ox: 2, oy: 0.75, type: 'social' },
    ] },
  { id: "bistro_chair", x: 7.5, y: 21.75, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "bistro_chair", x: 10, y: 21.75, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "cafe_table", x: 11, y: 21, w: 1.5, h: 1.5, layer: 'below', anchors: [
    { name: "cafe_seat_2", ox: -0.5, oy: 0.75, type: 'social' },
    { name: "cafe_seat_3", ox: 2, oy: 0.75, type: 'social' },
    ] },
  { id: "bistro_chair", x: 10.5, y: 21.75, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "bistro_chair", x: 13, y: 21.75, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "high_table", x: 8, y: 23, w: 2, h: 2, layer: 'below', anchors: [
    { name: "cafe_high_0", ox: 0, oy: 2.5, type: 'social' },
    { name: "cafe_high_1", ox: 2, oy: 2.5, type: 'social' },
    ] },
  { id: "bar_stool", x: 8, y: 24.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "bar_stool", x: 10, y: 24.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "service_counter", x: 11, y: 23.5, w: 3, h: 0.5, layer: 'below', anchors: [] },
  { id: "tall_plant", x: 7, y: 20, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "tall_plant", x: 13, y: 20, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "pendant_light", x: 8.75, y: 21.75, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "pendant_light", x: 11.75, y: 21.75, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
];

// ─── Gaming Lounge (rows 20-24, cols 15-38) ───
export const gamingProps: PropPlacement[] = [
  { id: "gaming_pc_station", x: 16, y: 21, w: 1.5, h: 1, layer: 'below', anchors: [{ name: "gaming_0", ox: 0.75, oy: 1.5, type: 'social' }] },
  { id: "gaming_chair", x: 16.75, y: 22.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "gaming_pc_station", x: 18, y: 21, w: 1.5, h: 1, layer: 'below', anchors: [{ name: "gaming_1", ox: 0.75, oy: 1.5, type: 'social' }] },
  { id: "gaming_chair", x: 18.75, y: 22.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "gaming_pc_station", x: 20, y: 21, w: 1.5, h: 1, layer: 'below', anchors: [{ name: "gaming_2", ox: 0.75, oy: 1.5, type: 'social' }] },
  { id: "gaming_chair", x: 20.75, y: 22.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "gaming_pc_station", x: 22, y: 21, w: 1.5, h: 1, layer: 'below', anchors: [{ name: "gaming_3", ox: 0.75, oy: 1.5, type: 'social' }] },
  { id: "gaming_chair", x: 22.75, y: 22.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "console_tv", x: 25, y: 20, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "console_sofa", x: 24, y: 22, w: 3.5, h: 1.5, layer: 'below', anchors: [
    { name: "console_0", ox: 0.5, oy: 0, type: 'social' },
    { name: "console_1", ox: 1.75, oy: 0, type: 'social' },
    { name: "console_2", ox: 3, oy: 0, type: 'social' },
    ] },
  { id: "arcade_cabinet", x: 29, y: 20.5, w: 1, h: 1.5, layer: 'below', anchors: [{ name: "arcade_0", ox: 0.5, oy: 2, type: 'social' }] },
  { id: "arcade_cabinet", x: 31, y: 20.5, w: 1, h: 1.5, layer: 'below', anchors: [{ name: "arcade_1", ox: 0.5, oy: 2, type: 'social' }] },
  { id: "bean_bag", x: 33, y: 21, w: 1, h: 1, layer: 'below', anchors: [{ name: "bean_0", ox: 0.5, oy: 0, type: 'rest' }] },
  { id: "bean_bag", x: 34.5, y: 21, w: 1, h: 1, layer: 'below', anchors: [{ name: "bean_1", ox: 0.5, oy: 0, type: 'rest' }] },
  { id: "bean_bag", x: 36, y: 21, w: 1, h: 1, layer: 'below', anchors: [{ name: "bean_2", ox: 0.5, oy: 0, type: 'rest' }] },
  { id: "bean_bag", x: 33, y: 23, w: 1, h: 1, layer: 'below', anchors: [{ name: "bean_3", ox: 0.5, oy: 0, type: 'rest' }] },
  { id: "bean_bag", x: 34.5, y: 23, w: 1, h: 1, layer: 'below', anchors: [{ name: "bean_4", ox: 0.5, oy: 0, type: 'rest' }] },
  { id: "bean_bag", x: 36, y: 23, w: 1, h: 1, layer: 'below', anchors: [{ name: "bean_5", ox: 0.5, oy: 0, type: 'rest' }] },
  { id: "snack_counter", x: 37, y: 20, w: 2, h: 0.5, layer: 'below', anchors: [] },
  { id: "sound_system", x: 15, y: 20, w: 1, h: 0.5, layer: 'below', anchors: [] },
  { id: "rgb_led_strip", x: 15, y: 24, w: 23, h: 0.5, layer: 'above', anchors: [] },
];

// ─── Terrace (rows 26-31, cols 1-14) ───
export const terraceProps: PropPlacement[] = [
  { id: "outdoor_dining_set", x: 2, y: 27, w: 3, h: 3, layer: 'below', anchors: [
    { name: "terrace_dine_0", ox: 0, oy: 3.5, type: 'social' },
    { name: "terrace_dine_1", ox: 1.5, oy: 3.5, type: 'social' },
    { name: "terrace_dine_2", ox: 3, oy: 3.5, type: 'social' },
    { name: "terrace_dine_3", ox: 0, oy: -0.5, type: 'social' },
    ] },
  { id: "outdoor_dining_set", x: 6, y: 27, w: 3, h: 3, layer: 'below', anchors: [
    { name: "terrace_dine_4", ox: 0, oy: 3.5, type: 'social' },
    { name: "terrace_dine_5", ox: 1.5, oy: 3.5, type: 'social' },
    { name: "terrace_dine_6", ox: 3, oy: 3.5, type: 'social' },
    { name: "terrace_dine_7", ox: 0, oy: -0.5, type: 'social' },
    ] },
  { id: "lounge_chair", x: 10, y: 26, w: 1.5, h: 2, layer: 'below', anchors: [{ name: "terrace_rest_0", ox: 0.75, oy: 0, type: 'rest' }] },
  { id: "lounge_chair", x: 12, y: 26, w: 1.5, h: 2, layer: 'below', anchors: [{ name: "terrace_rest_1", ox: 0.75, oy: 0, type: 'rest' }] },
  { id: "umbrella", x: 3.5, y: 27, w: 2, h: 2, layer: 'above', anchors: [] },
  { id: "umbrella", x: 7.5, y: 27, w: 2, h: 2, layer: 'above', anchors: [] },
  { id: "planter", x: 1, y: 30, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "planter", x: 10, y: 30, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "planter", x: 13, y: 30, w: 2, h: 1, layer: 'below', anchors: [] },
  { id: "outdoor_heater", x: 5, y: 30, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "outdoor_heater", x: 9, y: 30, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "weather_awning", x: 1, y: 26, w: 13, h: 1, layer: 'above', anchors: [] },
];

// ─── Green Area (rows 26-31, cols 16-38) ───
export const greenProps: PropPlacement[] = [
  { id: "mature_tree", x: 17, y: 26, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "mature_tree", x: 22, y: 26, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "mature_tree", x: 35, y: 26, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "mature_tree", x: 17, y: 30, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "mature_tree", x: 35, y: 30, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "garden_bench", x: 19, y: 27, w: 3, h: 1, layer: 'below', anchors: [
    { name: "green_bench_0", ox: 0, oy: 1.5, type: 'rest' },
    { name: "green_bench_1", ox: 3, oy: 1.5, type: 'rest' },
    ] },
  { id: "garden_bench", x: 32, y: 27, w: 3, h: 1, layer: 'below', anchors: [
    { name: "green_bench_2", ox: 0, oy: 1.5, type: 'rest' },
    { name: "green_bench_3", ox: 3, oy: 1.5, type: 'rest' },
    ] },
  { id: "meditation_circle", x: 25, y: 27, w: 4, h: 4, layer: 'below', anchors: [
    { name: "meditate_0", ox: 1, oy: 1, type: 'rest' },
    { name: "meditate_1", ox: 3, oy: 1, type: 'rest' },
    { name: "meditate_2", ox: 2, oy: 3, type: 'rest' },
    ] },
  { id: "water_fountain", x: 27, y: 31, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "walking_path", x: 16, y: 28, w: 22, h: 1, layer: 'below', anchors: [] },
  { id: "walking_path", x: 25, y: 26, w: 1, h: 6, layer: 'below', anchors: [] },
  { id: "planter_varied", x: 30, y: 26, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "planter_varied", x: 32, y: 26, w: 2, h: 2, layer: 'below', anchors: [] },
  { id: "planter_varied", x: 30, y: 30, w: 1, h: 1, layer: 'below', anchors: [] },
  { id: "outdoor_lighting", x: 20, y: 26, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "outdoor_lighting", x: 30, y: 26, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
  { id: "outdoor_lighting", x: 25, y: 32, w: 0.5, h: 0.5, layer: 'above', anchors: [] },
];

// ─── Architect (rows 34-38, cols 4-14) ───
export const architectProps: PropPlacement[] = [
  { id: "drafting_table", x: 5, y: 35, w: 2.5, h: 2, layer: 'below', anchors: [{ name: "architect_draft_0", ox: 1.25, oy: 2.5, type: 'work' }] },
  { id: "drafting_table", x: 8, y: 35, w: 2.5, h: 2, layer: 'below', anchors: [{ name: "architect_draft_1", ox: 1.25, oy: 2.5, type: 'work' }] },
  { id: "drafting_stool", x: 6, y: 37.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "drafting_stool", x: 9, y: 37.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "cad_workstation", x: 11, y: 35, w: 2, h: 1.5, layer: 'below', anchors: [{ name: "architect_cad", ox: 1, oy: 2, type: 'work' }] },
  { id: "ergonomic_chair", x: 12, y: 37, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "blueprint_storage", x: 4, y: 37, w: 1.5, h: 1, layer: 'below', anchors: [] },
  { id: "blueprint_storage", x: 13, y: 37, w: 1.5, h: 1, layer: 'below', anchors: [] },
  { id: "model_showcase", x: 4, y: 34, w: 2, h: 0.5, layer: 'below', anchors: [] },
  { id: "model_showcase", x: 12, y: 34, w: 2, h: 0.5, layer: 'below', anchors: [] },
  { id: "material_library", x: 6, y: 34, w: 3, h: 0.5, layer: 'below', anchors: [] },
  { id: "presentation_easel", x: 10, y: 38, w: 1, h: 1, layer: 'below', anchors: [{ name: "architect_present", ox: 0.5, oy: 1.5, type: 'work' }] },
  { id: "private_meeting_table", x: 6, y: 38, w: 2, h: 1.5, layer: 'below', anchors: [
    { name: "architect_meet_0", ox: 0, oy: 2, type: 'social' },
    { name: "architect_meet_1", ox: 2, oy: 2, type: 'social' },
    ] },
  { id: "meeting_chair", x: 6, y: 39.5, w: 1, h: 1, layer: 'above', anchors: [] },
  { id: "meeting_chair", x: 8, y: 39.5, w: 1, h: 1, layer: 'above', anchors: [] },
];

export const allCampusProps: PropPlacement[] = [
  ...dataCenterProps,
  ...auditoriumProps,
  ...nocProps,
  ...scrumProps,
  ...coworkProps,
  ...ceoProps,
  ...huddleProps,
  ...snackProps,
  ...cafeProps,
  ...gamingProps,
  ...terraceProps,
  ...greenProps,
  ...architectProps,
];

/** @deprecated Use allCampusProps instead */
export const ALL_PROPS = allCampusProps;

export const tileMap: Record<string, string> = {
  "server_rack": "rack.png",
  "crac_cooling_unit": "air-conditioner.png",
  "ups_cabinet": "shelving.png",
  "noc_desk": "desk.png",
  "ergonomic_chair": "gaming-chair-a.png",
  "data_display_wall": "big-tv.png",
  "biometric_panel": "tablet.png",
  "fire_suppression_panel": "poster.png",
  "panoramic_screen": "big-tv.png",
  "podium": "desk.png",
  "speaker_tower": "speaker.png",
  "auditorium_seats": "sofa-a.png",
  "stage_light": "lamp-a.png",
  "video_camera": "tablet.png",
  "noc_screen_wall": "big-tv.png",
  "desk_monitor": "desk.png",
  "war_table": "table-large.png",
  "tall_plant": "plant-tree.png",
  "whiteboard_glass": "window-a.png",
  "scrum_table": "table-large.png",
  "sprint_board": "poster.png",
  "standing_desk": "desk-alt.png",
  "hot_desk": "desk.png",
  "monitor_arm": "monitor-flat.png",
  "phone_booth": "door-glass.png",
  "lounge_sofa": "sofa-a.png",
  "lounge_chair": "chair-a.png",
  "executive_desk": "desk-alt.png",
  "bookshelf": "shelving.png",
  "coffee_table": "table-small.png",
  "meeting_table": "table-small.png",
  "huddle_screen": "big-tv.png",
  "round_table": "table-small.png",
  "bar_counter": "kitchen-table.png",
  "bar_stool": "stool.png",
  "fridge": "fridge.png",
  "microwave": "microwave.png",
  "espresso_machine": "kettle.png",
  "cafe_table": "table-small.png",
  "bistro_chair": "chair-b.png",
  "plant_small": "plant-small.png",
  "lamp": "lamp-b.png",
  "gaming_pc": "pc-tower.png",
  "gaming_monitor": "monitor-curved.png",
  "gaming_chair": "gaming-chair-d.png",
  "console_station": "console-switch.png",
  "bean_bag": "pillow.png",
  "big_tv": "big-tv.png",
  "speakers": "speaker.png",
  "outdoor_chair": "chair-c.png",
  "outdoor_table": "table-small.png",
  "planter": "plant-bush.png",
  "garden_bench": "sofa-c.png",
  "tree": "plant-tree.png",
  "cactus_plant": "cactus.png",
  "sunflower_patch": "sunflower.png",
  "drafting_table": "desk.png",
  "blueprint_display": "big-tv.png",
  "model_shelf": "shelving.png",
  "architect_monitors": "monitor-curved.png",
  "trash_bin": "trash-bin.png",
  "mug": "mug.png",
  "keyboard": "keyboard.png",
  "laptop": "laptop.png",
  "poster": "poster.png",
  "carpet": "carpet.png",
  "window": "window-a.png",
  "door": "door-blue-sheet.png",
  "console_nes": "console-nes.png",
  "cooling_unit": "air-conditioner.png",
  "monitoring_wall": "big-tv.png",
  "projection_screen": "big-tv.png",
  "tiered_seats": "chair-a.png",
  "sound_control": "speaker.png",
  "alert_dashboard": "big-tv.png",
  "workstation": "desk.png",
  "whiteboard_wall": "poster.png",
  "standing_table": "table-small.png",
  "mobile_stool": "stool.png",
  "sticky_supply": "mug.png",
  "monitoring_desk": "desk.png",
  "monitor_workstation": "desk.png",
  "communication_panel": "tablet.png",
  "collaboration_table": "table-small.png",
  "storage_locker": "shelving.png",
  "executive_chair": "gaming-chair-b.png",
  "l_shaped_sofa": "sofa-a.png",
  "meeting_chair": "chair-a.png",
  "art_display": "poster.png",
  "mini_fridge": "fridge.png",
  "huddle_glass_wall": "window-a.png",
  "pod_chair": "chair-b.png",
  "wall_screen": "big-tv.png",
  "whiteboard": "poster.png",
};
